### ISSUE TITLE
Packetize everything to improve extensibility and readability

### ISSUE THREAD

**Issue by ysl3000** [NickAcPT/Lithium#15]
Look at my commits here they reduce failures and improve extensebility
Forge:
https://github.com/Craftstuebchen/Lithium-Forge/tree/dev
Spigot:
https://github.com/Craftstuebchen/Lithium-Spigot/tree/dev
Backend:
https://github.com/Craftstuebchen/Lithium-Backend/tree/dev
LithiumTest
https://github.com/Craftstuebchen/Lithium-TestPlugin/tree/dev

**Comment by NickAcPT** [comment]
Those will be merged when you feel they're ready.

Keeping this issue open until then.

**Comment by NickAcPT** [comment]
Changes merged.
